export const tempShapeslist = [
  {
    code: 'R',
    isSelected: false,
    name: 'round',
    label: 'ROUND',
    synonyms: 'BR,RB,RD,RBC,ROUND BRILLIANT,ROUND,RO,RND,R',
    order: 1,
  },
  {
    code: 'E',
    isSelected: false,
    name: 'emerald',
    label: 'EMERALD',
    synonyms: 'EM,EC,EMERALD,EMRALD,EMRL,FBD',
    order: 2,
  },
  {
    code: 'P',
    isSelected: false,
    name: 'princess',
    label: 'PRINCESS',
    synonyms: 'PRN,PR,PRIN,PN,PC,MDSQB,SMB,PRINCESS,PRI,PRINCES,RMB',
    order: 3,
  },
  {
    code: 'CU',
    isSelected: false,
    name: 'cushion',
    label: 'CUSHION',
    synonyms: 'C,CUX,CU,CUSH,CUSHION,CUS,CUSHION BRILLIANT,CS,LCB,CUSION,CMB',
    order: 4,
  },
  {
    code: 'H',
    isSelected: false,
    name: 'heart',
    label: 'HEART',
    synonyms: 'HS,HT,HEART,HRT,HE,HB,MHB',
    order: 4,
  },

  {
    code: 'LR',
    isSelected: false,
    name: 'radiant',
    label: 'RADIANT',
    synonyms: 'LR,RA,CSMB,LONG RADIANT,CRMB',
    order: 5,
  },
  {
    code: 'PE',
    isSelected: false,
    name: 'pear',
    label: 'PEAR',
    synonyms: 'PS,PSH,PEAR,PB,PE,PMB',
    order: 6,
  },
  {
    code: 'O',
    isSelected: false,
    name: 'oval',
    label: 'OVAL',
    synonyms: 'OV,OVAL,OL,OB,OMB',
    order: 7,
  },
  {
    code: 'M',
    isSelected: false,
    name: 'marquise',
    label: 'MARQUISE',
    synonyms: 'MQB,MQ,MARQUISE,MAQ,MB',
    order: 8,
  },
  {
    code: 'SE',
    isSelected: false,
    name: 'square emerald',
    label: 'SQ EMERALD',
    synonyms:
      'SQE,SQEM,SQUARE EMERALD,SQ,Sq. Emerald,SQ.EMERALD,SE,SQ Emerald,SQUARE EMRALD,SEM,S.EMERALD,CSSC',
    order: 9,
  },
  {
    code: 'ASH,BUG,CB,LCU,OCU,SQR,TR',
    isSelected: false,
    name: 'Other',
    label: 'Other',
    synonyms:
      'A,CSS.AC,ASSCHER,ASH,BUGGET,CU BRILLIANT,CB,CUS.BR…T,CSMB,TRILLIENT,TR,Modified Triangular Brilliant',
    order: 25,
  },
];
export const tempSizeList = [
  {
    code: 6,
    from: 0.18,
    isSelected: false,
    label: '0.18 - 0.22',
    name: 6,
    order: 6,
    to: 0.199,
  },
  {
    code: 7,
    from: 0.2,
    isSelected: false,
    label: '0.18 - 0.22',
    name: 7,
    order: 7,
    to: 0.229,
  },
  {
    code: 8,
    from: 0.23,
    isSelected: false,
    label: '0.23 - 0.29',
    name: 8,
    order: 8,
    to: 0.249,
  },
  {
    code: 9,
    from: 0.25,
    isSelected: false,
    label: '0.23 - 0.29',
    name: 9,
    order: 9,
    to: 0.299,
  },
  {
    code: 10,
    from: 0.3,
    isSelected: false,
    label: '30s',
    name: 10,
    order: 10,
    to: 0.349,
  },
  {
    code: 11,
    from: 0.35,
    isSelected: false,
    label: '30s',
    name: 11,
    order: 11,
    to: 0.369,
  },
  {
    code: 12,
    from: 0.37,
    isSelected: false,
    label: '30s',
    name: 12,
    order: 12,
    to: 0.399,
  },
  {
    code: 13,
    from: 0.4,
    isSelected: false,
    label: '40s',
    name: 13,
    order: 13,
    to: 0.449,
  },
  {
    code: 14,
    from: 0.45,
    isSelected: false,
    label: '40s',
    name: 14,
    order: 14,
    to: 0.469,
  },
  {
    code: 15,
    from: 0.47,
    isSelected: false,
    label: '40s',
    name: 15,
    order: 15,
    to: 0.499,
  },
  {
    code: 16,
    from: 0.5,
    isSelected: false,
    label: '50s - 60s',
    name: 16,
    order: 16,
    to: 0.549,
  },
  {
    code: 17,
    from: 0.55,
    isSelected: false,
    label: '50s - 60s',
    name: 17,
    order: 17,
    to: 0.599,
  },
  {
    code: 22,
    from: 0.77,
    isSelected: false,
    label: '70s - 80s',
    name: 22,
    order: 22,
    to: 0.799,
  },
  {
    code: 32,
    from: 1.4,
    isSelected: false,
    label: '1ct',
    name: 32,
    order: 32,
    to: 1.499,
  },
];
export const tempSearch_color = [
  {
    code: 1,
    isSelected: false,
    label: 'D',
    name: 'D',
    order: 1,
    synonyms: 'D,D+,D-',
  },
  {
    code: 2,
    isSelected: false,
    label: 'E',
    name: 'E',
    order: 2,
    synonyms: 'E,E+,E-',
  },
  {
    code: 3,
    isSelected: false,
    label: 'F',
    name: 'F',
    order: 3,
    synonyms: 'F,F+,F-',
  },
  {
    code: 4,
    isSelected: false,
    label: 'G',
    name: 'G',
    order: 4,
    synonyms: 'G,G+,G-',
  },
  {
    code: 5,
    isSelected: false,
    label: 'H',
    name: 'H',
    order: 5,
    synonyms: 'H,H+,H-',
  },
  {
    code: 6,
    isSelected: false,
    label: 'I',
    name: 'I',
    order: 6,
    synonyms: 'I,I+,I-',
  },
  {
    code: 7,
    isSelected: false,
    label: 'J',
    name: 'J',
    order: 7,
    synonyms: 'J,J+,J-',
  },
  {
    code: 7,
    isSelected: false,
    label: 'M',
    name: 'M',
    order: 7,
    synonyms: 'M,M+,M-',
  },
];
export const tempClarities_list = [
  {
    code: 12,
    isSelected: false,
    label: 'FL',
    name: 'FL',
    order: 1,
    synonyms: 'FL',
  },
  {
    code: 1,
    isSelected: false,
    label: 'IF',
    name: 'IF',
    order: 2,
    synonyms: 'IF,IF+,IF-,INTERNALLY FLAWLESS',
  },
  {
    code: 2,
    isSelected: false,
    label: 'VVS1',
    name: 'VVS1',
    order: 3,
    synonyms: 'VVS1,VVS1+,VVS1-,VVS 1',
  },
  {
    code: 3,
    isSelected: false,
    label: 'VVS2',
    name: 'VVS2',
    order: 4,
    synonyms: 'VVS2,VVS2+,VVS2-,VVS 2',
  },
  {
    code: 4,
    isSelected: false,
    label: 'VS1',
    name: 'VS1',
    order: 5,
    synonyms: 'VS1,VS1+,VS1-,VS 1',
  },
  {
    code: 5,
    isSelected: false,
    label: 'VS2',
    name: 'VS2',
    order: 6,
    synonyms: 'VS2,VS2+,VS2-,VS 2',
  },
  {
    code: 6,
    isSelected: false,
    label: 'SI1',
    name: 'SI1',
    order: 7,
    synonyms: 'SI1,SI1+,SI1-,SI 1',
  },
  {
    code: 7,
    isSelected: false,
    label: 'SI2',
    name: 'SI2',
    order: 8,
    synonyms: 'SI2,SI2+,SI2-,SI 2',
  },
  {
    code: 8,
    isSelected: false,
    label: 'SI3',
    name: 'SI3',
    order: 9,
    synonyms: 'SI3,SI3+,SI3-',
  },
  {
    code: 9,
    isSelected: false,
    label: 'I1',
    name: 'I1',
    order: 10,
    synonyms: 'I1,I1+,I1-',
  },
  {
    code: 10,
    isSelected: false,
    label: 'I2',
    name: 'I2',
    order: 11,
    synonyms: 'I2,I2+,I2-',
  },
  {
    code: 11,
    isSelected: false,
    label: 'I3',
    name: 'I3',
    order: 12,
    synonyms: 'I3,I3+,I3-',
  },
];
export const tempCut_list = [
  {
    code: 1,
    isSelected: false,
    label: 'EX1',
    name: 'EX1',
    order: 1,
    synonyms: 'EX1',
  },
  {
    code: 2,
    isSelected: false,
    label: 'EX',
    name: 'EX',
    order: 2,
    synonyms: 'EX',
  },
  {
    code: 3,
    isSelected: false,
    label: 'VG',
    name: 'VG',
    order: 3,
    synonyms: 'VG',
  },
  {
    code: 4,
    isSelected: false,
    label: 'GD',
    name: 'GD',
    order: 4,
    synonyms: 'GD',
  },
  {
    code: 5,
    isSelected: false,
    label: 'FR',
    name: 'FR',
    order: 5,
    synonyms: 'FR',
  },
];
export const tempSym_list = [
  {
    code: 1,
    isSelected: false,
    label: 'EX',
    name: 'EX',
    order: 1,
    synonyms: 'EX',
  },
  {
    code: 2,
    isSelected: false,
    label: 'VG',
    name: 'VG',
    order: 2,
    synonyms: 'VG',
  },
  {
    code: 3,
    isSelected: false,
    label: 'GD',
    name: 'GD',
    order: 3,
    synonyms: 'GD',
  },
  {
    code: 4,
    isSelected: false,
    label: 'FR',
    name: 'FR',
    order: 4,
    synonyms: 'FR',
  },
];
export const tempPol_list = [
  {
    code: 1,
    isSelected: false,
    label: 'EX',
    name: 'EX',
    order: 1,
    synonyms: 'EX',
  },
  {
    code: 2,
    isSelected: false,
    label: 'VG',
    name: 'VG',
    order: 2,
    synonyms: 'VG',
  },
  {
    code: 3,
    isSelected: false,
    label: 'GD',
    name: 'GD',
    order: 3,
    synonyms: 'GD',
  },
  {
    code: 4,
    isSelected: false,
    label: 'FR',
    name: 'FR',
    order: 4,
    synonyms: 'FR',
  },
];
export const tempFlor_list = [
  {
    code: 1,
    isSelected: false,
    label: 'NONE',
    name: 'NONE',
    order: 1,
    synonyms: 'NONE',
  },
  {
    code: 2,
    isSelected: false,
    label: 'FAIN',
    name: 'FAIN',
    order: 2,
    synonyms: 'FAIN',
  },
  {
    code: 3,
    isSelected: false,
    label: 'MED',
    name: 'MED',
    order: 3,
    synonyms: 'MED',
  },
  {
    code: 4,
    isSelected: false,
    label: 'STG',
    name: 'STG',
    order: 4,
    synonyms: 'STG',
  },
  {
    code: 5,
    isSelected: false,
    label: 'VSTG',
    name: 'VSTG',
    order: 5,
    synonyms: 'VSTG',
  },
];
